apiVersion: skaffold/v2beta5
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: ronaimate/placeholder
      jib: { }
deploy:
  kubectl:
    manifests:
      - k8s/placeholder-deployment.yml